variables:
  IMAGE_NAME: oluwaseuna/pythonapp
  IMAGE_TAG: appv1.1

stages:
  - test
  - build
  - deploy

run_tests:
  image: python:3.9-slim-buster
  stage: test
  before_script:
    - apt-get update && apt-get install make -y
  script:
    - make test

build_image:
  image: docker:24.0.6
  stage: build
  needs:
    - run_tests
  services:
    - docker:24.0.6-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $USERNAME -p $PASSWORD
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

# deploy:
#   stage: deploy
#   needs:
#     - build_image
#   before_script:
#     - chmod 400 $SSH_KEY
#   script:
#     - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@3.16.68.108 "
#         docker login -u $USERNAME -p $PASSWORD &&
#         docker ps -aq | xargs docker stop | xargs docker rm &&
#         docker run -d -p 5000:5000 $IMAGE_NAME:$IMAGE_TAG"
